### PR TITLE
use SqlConnectionStringBuilder to generate connection string

### PR DESCRIPTION
**Pull request by ChaunceyJ**
Hi, I just used SqlConnectionStringBuilder to generate connection string to replace the original connect string. Then when I.connect the SQL Server the error happened.

### CODE REVIEW

**Comment by Jtango18** [comment]
It's not clear why you need System.Memory added at all for this? I've used connection builder to hit a Database without any problems. What functionality is System.Memory giving you?
Screen Shot 2020-10-27 at 15 00 30

**Comment by ChaunceyJ** [comment]
I am not using System.Memory. The problem is that the program will throw an exception when executing the `cmd.Connection.Open();` . The exception is the following.
```
[2020/10/27 上午4:17:32] Executed 'Repro1717' (Failed, Id=b6dec4ea-f16e-4afe-834b-b8ad12dbdbdd)
[2020/10/27 上午4:17:32] System.Private.CoreLib: Exception while executing function: Repro1717. Microsoft.Data.SqlClient: Could not load file or assembly 'System.Memory, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
[2020/10/27 上午4:17:32] . System.Private.CoreLib: Could not load the specified file.
```
The exception will be thrown no matter if I add System.Memory or not.

**Comment by Jtango18** [comment]
I'm afraid I'm completely unable to replicate this. The code I have above works perfectly for me every single time I run it. The only difference I could see what that you had added a reference to System.Memory, so thought it might be related to that. 

Can I ask - if you create a DB in Azure rather than using local host, do you have the same issue?

**Comment by ChaunceyJ** [comment]
OK, thank you so much. I think maybe it is related to the environment on my computer. I will try to use the DB in Azure.

**Pull request closed without merging**
